version: "3.8"

services:
  bank-accounting:
    image: $DOCKER_IMAGE
    container_name: bank-accounting
    command: bundle exec rails server --binding=0.0.0.0
    env_file:
      - .env
    ports:
      - $EXTERNAL_PORT:3000
    volumes:
      - .:/app
      - gems_home:/gems
      - user_home:/home/dev
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: postgres:14.5-alpine
    container_name: bank-accounting-db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  gems_home:
    name: bank-accounting-gems-home
  user_home:
    name: bank-accounting-user-home
  db_data:
    name: bank-accounting-pgdb14
