default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL") %>

# for test and development databases, DATABSE_URL must provide a Postgres URI
# without the included database name.
development:
  <<: *default
  database: bank_accounting_development

test:
  <<: *default
  database: bank_accounting_test

# The DATABASE_URL production environment is expected to provide a fully
# qualified Postgres URI.
production:
  <<: *default
