#!/usr/bin/env bash

set -euo pipefail

dir="$(realpath "$(dirname "$0")")"

cd "$dir" || exit 1

deps="$(../builder/current-image)"
files=$(shasum -a 256 build current-image Dockerfile Dockerfile.dockerignore)
tag=$(echo "$files@$deps" | shasum -a 256 | cut -c1-7)

echo "local-development/bank-accounting:$tag"
